server:
  port: 8080
spring:
  application:
    name: "pruebaTecnica"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapters:
  r2dbc:
    initialization-mode: always
    schema: classpath:schema.sql
    pool:
      enabled: false
      name: api-postgres-connection-pool
      initial-size: 5
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1
    properties:
      schema: public
      database: nequi_prueba_dev
      host: "${SPRING_R2DBC_URL:us-east-1.rds.amazonaws.com}"
      username: "${SPRING_R2DBC_USERNAME:dbadmin}" 
      password: "${SPRING_R2DBC_PASSWORD:123456"
      port: 5432          
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
aws:
  region: 
  secretName: "${SPRING_R2DBC_URL}"
  secretNameDB: "${SPRING_R2DBC_USERNAME}"
  secretKeyToken: "${SPRING_R2DBC_PASSWORD}"





